settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: omikuji
  path: .
  commands:
    install:
      status: true
      method: go build -o app.out ./server.go
    run:
      status: true
      method: ./app.out
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
